apiVersion: v1
kind: Pod
metadata:
  name: react-redux
  labels:
    name: react-redux
spec:
  containers:
  - name: react-redux
    image: eu.gcr.io/recet-demo/hello-ci:test
    ports:
      - containerPort: 3000
        name: http
    command: ["sh", "-c", "sleep 100000000"]
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "400Mi"
        cpu: "100m"
      limits:
        memory: "750Mi"
        cpu: "1200m"
  restartPolicy: Always
