apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-redux
  #namespace: documentation
  labels:
    app: react-redux
spec:
  replicas: 2
  selector:
    matchLabels:
      name: react-redux
  template:
    metadata:
      labels:
        name: react-redux
    spec:
      containers:
      - name: react-redux
        image: eu.gcr.io/recet-demo/hello-ci:82e38c47138751d865b56774af8c2e74ba8fe166
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "200m"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 5