apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-redux
  #namespace: documentation
  labels:
    app: react-redux
spec:
  replicas: 2
  selector:
    matchLabels:
      name: react-redux
  template:
    metadata:
      labels:
        name: react-redux
    spec:
      containers:
      - name: react-redux
        image: eu.gcr.io/recet-demo/hello-ci:61dd9608b36be945311fb2d5aea983c5adb85b90
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "200m"
 #       command: ["sh", "-c", "sleep 100000000"]
 #       readinessProbe:
 #         tcpSocket:
 #           port: 80
 #         initialDelaySeconds: 15
 #         timeoutSeconds: 5